import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

interface CardProps {
  url: string
  title: string
  description: string
}

const Card: React.FC<CardProps> = (props) => {
  return (
    <a href={props.url} className="m-4 p-6 text-left border border-neutral-200 dark:border-neutral-800 hover:border-blue-600 focus:border-blue-600 active:border-blue-600 rounded-lg max-w-xs">
      <h2 className="text-left mb-4 text-2xl">{props.title}</h2>
      <p className="m-0 text-xl">{props.description}</p>
    </a>
  )
}

const Home: NextPage = () => {
  return (
    <div className="text-black dark:text-white bg-white dark:bg-black px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 flex-1 flex flex-col justify-center items-center">
        <h1 className="m-0 text-6xl text-center">
          Welcome to <a className="text-blue-600 hover:underline" href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="text-center my-8 text-xl">
          Get started by editing{' '}
          <code className="bg-neutral-200 dark:bg-neutral-800 rounded py-3 text-lg font-mono">
            pages/index.tsx
          </code>
        </p>

        <div className="flex items-center justify-center flex-col sm:flex-row sm:flex-wrap w-full sm:max-w-screen-md">
          <Card
            url="https://nextjs.org/docs"
            title="Documentation &rarr;"
            description="Find in-depth information about Next.js features and API."
            />
          <Card
            url="https://nextjs.org/learn"
            title="Learn &rarr;"
            description="Learn about Next.js in an interactive course with quizzes!"
            />
          <Card
            url="https://github.com/vercel/next.js/tree/canary/examples"
            title="Examples &rarr;"
            description="Discover and deploy boilerplate example Next.js projects."
          />
          <Card
            url="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy &rarr;"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <footer className="flex flex-1 py-8 border-t border-t-neutral-200 dark:border-t-neutral-800 justify-center items-center">
        <a
          className="flex justify-center items-center grow"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="h-full ml-2 dark:invert">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
